### ISSUE TITLE
Deprecate methods to create a cookie

### ISSUE THREAD

**Issue by rishimittal2003** [AdobeDocs/launch.en#12]
Issue in ./help/extension-reference/web/adobe-analytics-extension/overview.md

Under General > Enable EU Compliance for Adobe Analytics

The method to set a cookie as described on the page should be:
_satellite.cookie.set("sat_track", "false");
 or
_satellite.cookie.set("sat_track", "true");

_satellite.setCookie is deprecated in Launch

**Comment by srhoades-adobe** [comment]
Fixed issue.
