### ISSUE TITLE
"Adobe opt-in object" link is broken

### ISSUE THREAD

**Issue by pgangwani** [AdobeDocs/launch.en#21]
Issue in ./help/launch-reference/client-side-information/deploy-javascript-tags-to-opt-in-to-launch.md

Please fix 404 for "Adobe opt-in object" link 
https://docs.adobe.com/content/help/en/id-service/using/implementation-guides/opt-in-service/optin-overview.html

**Comment by srhoades-adobe** [comment]
Thanks for letting us know about the broken link. This should work now.
