### ISSUE TITLE
release notes missing

### ISSUE THREAD

**Issue by himanshu-pathak** [AdobeDocs/launch.en#24]
Issue in ./help/extension-reference/web/experience-cloud-id-service-extension/experience-cloud-id-release-notes.md

The current release in catalog is 4.5.2. However, the document shows 4.4.1 as the latest release. Hard to track what all has changes since. Can this be updated please?

**Comment by thebenrob** [comment]
I'll pass the request along to the ECID team.

**Comment by thebenrob** [comment]
I've passed this along to the extension developers.

**Comment by jileeshs** [comment]
@thebenrob ,@himanshu-pathak ,
Is it still an issue?
The doc was updated long ago.
Please verify the [file](https://git.corp.adobe.com/mandody/launch.en/blob/3ac1a4440991e0f54b2553ce4f9032f8e04473d1/help/extension-reference/web/experience-cloud-id-service-extension/experience-cloud-id-release-notes.md) and let me know if any updates are needed.
