### ISSUE TITLE
Images do not align to the different actions

### ISSUE THREAD

**Issue by mikeatadobe** [AdobeDocs/launch.en#32]
Issue in ./help/extension-reference/web/marketo-munchkin-extension/overview.md

Images do not align to the different actions

**Comment by thebenrob** [comment]
I've passed this along to the developers.

**Comment by thebenrob** [comment]
Missing images:
- Click Link: https://d1a2d0h96mvhgv.cloudfront.net/3/101054/ae4e898f-4099-486d-a707-61211e67d713.png
- Visit Webpage: https://d1a2d0h96mvhgv.cloudfront.net/3/101054/f5a173cb-a236-462b-86ea-56105f34d8fa.png

**Comment by thebenrob** [comment]
This has been done.
