### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jkunz** [AdobeDocs/launch.en#33]
Issue in ./help/launch-reference/client-side-information/launch-object-reference.md
The link to "js-cookie usage documentation" breaks and ends up just pointing to community.adobe.com.

**Comment by thebenrob** [comment]
That link is definitely messed up with an extra redirect in it, but it does resolve for me.  I'll make the update, but if it helps in the meantime, the link should be https://www.npmjs.com/package/js-cookie#basic-usage

**Comment by thebenrob** [comment]
This is checked in on the internal repo and will be live with the next publish.
