### ISSUE TITLE
Please update with release notes for 4.4.1

### ISSUE THREAD

**Issue by Brontojoris** [AdobeDocs/launch.en#8]
The Experience Cloud ID Release Notes page shows releases up till 4.3.1, but Adobe Launch prompts to update to v4.4.1.

It would be good to know what the changes are before I upgrade the libraries.

Issue in ./help/extension-reference/web/experience-cloud-id-service-extension/experience-cloud-id-release-notes.md

**Comment by srhoades-adobe** [comment]
Release notes are current up to 4.4.1
